name: tmux-test
version: 0
summary: tmux - multiplex terminal
description: |
  tmux - multiplex temrinal

confinement: strict
grade: devel

apps:
  tmux:
    command: usr/bin/tmux

parts:
  tmux:
    plugin: autotools
    source: .
    build-packages:
      - libevent-dev
      - libncurses-dev
