name: tmux-test
version: 0
summary: tmux - multiplex terminal
description: |
  tmux - multiplex temrinal

confinement: classic
grade: devel

apps:
  tmux:
    command: tmux

parts:
  tmux:
    plugin: autotools
    source: .
    build-packages:
      - pkg-config
      - libevent-dev
      - libncurses-dev
